### ISSUE TITLE
getfield: too many arguments (expected 2), in Sink.jl

### ISSUE THREAD

**Issue by ignaciomartin** [JuliaDB/SQLite.jl#100]
A new version of CSV package generate this error:

![image](https://cloud.githubusercontent.com/assets/19220563/15214213/25962d70-184c-11e6-85e8-59533661ccc2.png)

while calling CSV.getfield(io,T,opts,row,col) function in Sink.jl

![image](https://cloud.githubusercontent.com/assets/19220563/15214234/41864e34-184c-11e6-82a1-2ca64d08fec0.png)

**Comment by felipenoris** [comment]
I can reproduce that running 
```julia
Pkg.test("SQLite")
```
With these packages checked out: DataStreams, SQLite, CSV.

**Comment by felipenoris** [comment]
@ignaciomartin I guess you can correct that changing `getfield` for `parsefield` for now.
