### ISSUE TITLE
StackOverflowError on any DB connection/creation on latest and 0.4.5

### ISSUE THREAD

**Issue by amellnik** [JuliaDB/SQLite.jl#102]
```julia
using SQLite
db = SQLite.DB()
````

```
LoadError: StackOverflowError:
while loading In[1], in expression starting on line 2

 in call at C:\Users\amellnik\.julia\v0.4\SQLite\src\SQLite.jl:48 (repeats 2 times)
```

I'm using the most recent tagged release of Compat (0.7.18) which seems like it might be related -- I assume this was introduced with https://github.com/JuliaDB/SQLite.jl/commit/198468bba9618bfa0b952d408c22001fbc35926f.

**Comment by felipenoris** [comment]
Hello! Are you using SQLite.jl v0.2.1 or the lastest commit on master branch?

**Comment by quinnj** [comment]
Uh, I'll take a look at it tonight.

**Comment by amellnik** [comment]
@felipenoris: This was on 6f51a51c51cb58b4b27366c08c3942edf695bb2f (I've since rolled back to aa777cbbc39fb6cb38dd1ade196a9e7342106f33 but can test the master on other systems if needed).

**Comment by felipenoris** [comment]
I can't reproduce the bug.
I'm using SQLite.jl, DataStreams.jl and CSV.jl on master branches.

**Comment by quinnj** [comment]
@felipenoris are you using julia 0.4 or 0.5? I think the problem is using the current master branches on 0.4. 0.5 should indeed be fine for now.

**Comment by felipenoris** [comment]
I tested on 0.4

**Comment by felipenoris** [comment]
@compat(String) does nothing, and defaults to AbstractString. Which calls DB(AbstractString) recursively.

**Comment by felipenoris** [comment]
These 3 PRs should fix tests on SQLite.jl, and also this bug.
https://github.com/JuliaDB/DataStreams.jl/pull/9
https://github.com/JuliaDB/CSV.jl/pull/22
https://github.com/JuliaDB/SQLite.jl/pull/103
