### ISSUE TITLE
Streaming from vanilla DataFrames is broken 

### ISSUE THREAD

**Issue by amellnik** [JuliaDB/SQLite.jl#108]
https://github.com/JuliaDB/SQLite.jl/commit/adfc7d54cd17e77202ac096b89e45d1abd9dfa94 and https://github.com/JuliaData/DataStreams.jl/commit/f507c7e31cf6272bbfcf92cbdcf1dd7cd54250dc changed a lot of things in the API, but also broke streaming from DataFrames with DataArray columns.  

On master, if we stream to a DataFrame we get a DataFrame with NullableArray columns:

```julia
 using DataFrames, DataStreams, NullableArrays, SQLite
# Make an in-memory database and a table with some values
db = SQLite.DB()
SQLite.query(db, "Create table temp (num INT, str TEXT)")
SQLite.query(db, "insert into temp VALUES (1, 'a')")
SQLite.query(db, "insert into temp VALUES (2, 'b')")
# Pull these back down
source = SQLite.Source(db, "select * from temp")
df = Data.stream!(source, DataFrame)
```
    2×2 DataFrames.DataFrame
    │ Row │ num         │ str           │
    ├─────┼─────────────┼───────────────┤
    │ 1   │ Nullable(1) │ Nullable("a") │
    │ 2   │ Nullable(2) │ Nullable("b") │

We can also stream this type of DataFrame back into the table:

```julia
sink = SQLite.Sink(db, df, "temp")
Data.stream!(df, sink)
```

    SQLite.Sink(Data.Schema:
    rows: 2	cols: 2
    Columns:
     "num"  Int64     
     "str"  UTF8String,SQLite.DB(in-memory),"temp",SQLite.Stmt(SQLite.DB(in-memory),Ptr{Void} @0x0000000035ae41b8))

However, suppose we wanted to add a few more rows.  If we construct a DataFrame using the normal constructors and try to stream it in:

```julia
df = DataFrame(num=Int64[5,6], str=UTF8String["g", "f"])
sink = SQLite.Sink(db, df, "temp")
Data.stream!(df, sink)
```

    LoadError: MethodError: `getbind!` has no method matching getbind!(::DataArrays.DataArray{Int64,1}, ::Int64, ::Int64, ::SQLite.Stmt)
    Closest candidates are:
      getbind!{T}(!Matched::NullableArrays.NullableArray{T,1}, ::Any, ::Any, ::Any)
      getbind!{T}(!Matched::Array{T,1}, ::Any, ::Any, ::Any)
      getbind!{T}(::Any, !Matched::Type{T}, ::Any, ::Any, !Matched::Any, !Matched::Any)
    while loading In[9], in expression starting on line 3

     in anonymous at C:\Users\amellnik\.julia\v0.4\SQLite\src\Sink.jl:60
     in transaction at C:\Users\amellnik\.julia\v0.4\SQLite\src\SQLite.jl:220
     in stream! at C:\Users\amellnik\.julia\v0.4\SQLite\src\Sink.jl:56

Right now the only workaround that I know of is to convert all vanilla DataFrames to NullableArrays DataFrames before streaming them in, as described in my comment here: https://github.com/JuliaStats/DataFrames.jl/issues/933.  

I'm still trying to get caught up on all these changes, and will see if I can create a PR that allows either type of DataFrame to be used.

I think this will pose a problem for users unfamiliar with this package, as it's not explicitly mentioned anywhere.  A set of minimal examples of streaming data DataFrame <--> SQLite might also be a good idea for the readme.md, as the examples shown in the tests are somewhat cryptic (and implicitly use NullableArrays constructors for DataFrames).

**Comment by quinnj** [comment]
Thanks for bringing this up; definitely important to support DataArray-based DataFrames for the time being. This is fixed on master (and will very soon be tagged in a new release).
