### ISSUE TITLE
Running the tests makes the package dirty, preventing it from being updated or removed

### ISSUE THREAD

**Issue by tkelman** [JuliaDB/SQLite.jl#109]
The tests modify the file `test/Chinook_Sqlite.sqlite`. This is very bad, as the package then won't be updated or removed by Pkg unless you manually reset the change. Either that file should be added to a gitignore, or some other scheme involving making a copy and comparing separate files would be better.

**Comment by felipenoris** [comment]
This is very annoying indeed. I suggest a `git checkout` at the end of the tests. I´ll send a PR with this suggestion.

**Comment by quinnj** [comment]
Ok, this is fixed now by [this line](https://github.com/JuliaDB/SQLite.jl/commit/cbedf7bbd2c242737e65dd1c1fadf0a6270ac0a1#diff-fce720c43af3c52c862fd7451c7374b8R19)

**Comment by tkelman** [comment]
would be good to gitignore the test version in case tests ever fail

**Comment by quinnj** [comment]
Good idea; change made.
