### ISSUE TITLE
Updates to DataStreams.jl (v.0.0.7) break SQLite

### ISSUE THREAD

**Issue by mirestrepo** [JuliaDB/SQLite.jl#111]
You can verify by upgrading DataStreams: v0.0.6 => v0.0.7

When running tests:

ERROR: LoadError: MethodError: `convert` has no method matching convert(::Type{DataFrames.DataFrame}, ::DataStreams.Data.Schema)
This may have arisen from a call to the constructor DataFrames.DataFrame(...),
since type constructors fall back to convert methods.WARNING: Error showing method candidates, aborted

 in stream! at /Users/isa/.julia/v0.4/SQLite/src/Source.jl:108

I believe the issue comes from changes to the interface to [DataFrame from schema](https://github.com/JuliaData/DataStreams.jl/blob/master/src/DataStreams.jl#L228)

**Comment by davidanthoff** [comment]
I'd also be really interested in a version that works with the latest DataStreams and on julia 0.5.

**Comment by quinnj** [comment]
Yeah, I probably should have capped the SQLite version when updating DataStreams. Sorry about that. For now, you should be able to do a `Pkg.checkout("DataStreams", "0.0.6")` to get back to a version of DataStreams that works with current SQLite. I'm also aiming to tag a new SQLite in the next few days.

**Comment by davidanthoff** [comment]
That doesn't work for me on julia 0.5, with DataStreams at v0.0.6 I get an error:
````
ERROR: LoadError: MethodError: no method matching reference(::SQLite.Source)
 in DataFrames.DataFrame(::SQLite.Source, ::Type{DataStreams.Data.Field}, ::Bool, ::Tuple{}) at C:\Users\anthoff\.julia\v0.5\DataStreams\src\DataStreams.jl:215
 in stream!(::SQLite.Source, ::Type{DataFrames.DataFrame}, ::Bool, ::Tuple{}) at C:\Users\anthoff\.julia\v0.5\DataStreams\src\DataStreams.jl:168
 in stream!(::SQLite.Source, ::Type{DataFrames.DataFrame}) at C:\Users\anthoff\.julia\v0.5\DataStreams\src\DataStreams.jl:175
 in include_from_node1(::String) at .\loading.jl:426
 in process_options(::Base.JLOptions) at .\client.jl:262
 in _start() at .\client.jl:318
while loading C:\Users\anthoff\.julia\v0.5\SQLite\test\runtests.jl, in expression starting on line 18
````
So, very much looking forward to a new tag for SQLite :)

**Comment by evanfields** [comment]
@quinnj Maybe I'm doing something dumb? I can't checkout version 0.0.6:
```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.6 (2016-06-19 17:16 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> Pkg.checkout("DataStreams", "0.0.6")
INFO: Checking out DataStreams 0.0.6...
fatal: Cannot update paths and switch to branch '0.0.6' at the same time.
Did you intend to checkout 'origin/0.0.6' which can not be resolved as commit?
ERROR: failed process: Process(`git '--work-tree=C:\Users\Evan\.julia\v0.4\DataStreams' '--git-dir=C:\Users\Evan\.julia\v0.4\DataStreams\.git' checkout -q -B 0.0.6 -t origin/0.0.6`, ProcessExited(128)) [128]
 in pipeline_error at process.jl:555
```

**Comment by maximsch2** [comment]
I'm not sure if this is related to `DataStreams` or not, but I'm getting the following error with newest SQLite, DataStreams and DataFrames on Julia 0.5 RC2:
```
LoadError: MethodError: no method matching reference(::SQLite.Source)
while loading In[3], in expression starting on line 1

 in DataFrames.DataFrame(::SQLite.Source, ::Type{DataStreams.Data.Field}, ::Bool, ::Tuple{}) at /home/grechkin/.julia/v0.5/DataStreams/src/DataStreams.jl:215
 in stream!(::SQLite.Source, ::Type{DataFrames.DataFrame}, ::Bool, ::Tuple{}) at /home/grechkin/.julia/v0.5/DataStreams/src/DataStreams.jl:168
 in query(::SQLite.DB, ::String) at /home/grechkin/.julia/v0.5/SQLite/src/Source.jl:143

```

**Comment by quinnj** [comment]
Yes, same issue. I'm actually working on this as we speak, hoping to have everything cleaned up, pushed, and re-tagged tonight.

**Comment by quinnj** [comment]
The new tag has been released, so a `Pkg.update()` should get everything working again.
