### ISSUE TITLE
My Installation uses wrong sqlite3.dll

### ISSUE THREAD

**Issue by lawless-m** [JuliaDB/SQLite.jl#115]
Hi,

I'm on a corporate locked down system so I can't change anything beyond my user profile.

But anyway, Pkg.add("SQLite") but when I start using SQLite 

It finds the wrong DLL which is on my current system

ERROR: ccall: could not find function sqlite3_create_function_v2 in library C:\Program Files (x86)\Novell\ZENworks\bin\sqlite3.DLL

Is there a way to force it to use G:\Julia-0.4.6\Git\mingw64\lib\sqlite3.8.8.3\sqlite3883.dll

(or whichever is appropriate ?)

Cheers

**Comment by nalimilan** [comment]
SQLite.jl's BinDeps commands should probably check for that function or a similar one via a validator before picking a DLL.

As a workaround, I think you can edit `.julia/SQLite/deps/deps.jl`.

**Comment by lawless-m** [comment]
That got me one step futher on

> db = SQLite.DB()
ERROR: ccall: could not find function sqlite3_open in library G:\Julia-0.4.6\Git\mingw64\lib\sqlite3.8.8.3\sqlite3883.dll
 in sqlite3_open at C:\Users\mwheath\.julia\v0.4\SQLite\src\api.jl:13

But it looks promising. I shall keep hunting tomorrow

**Comment by lawless-m** [comment]
SOLVED

I changed build.jl

- sqlite3_lib = library_dependency("sqlite3_lib", aliases = ["sqlite3","sqlite3-64","libsqlite3","libsqlite3-0"])
+ sqlite3_lib = library_dependency("sqlite3_lib", aliases = ["libsqlite3","libsqlite3-0"])

and ran Pkg.build("SQLite")

which then downloaded and installed libsqlite3-0


I can now run runtests.jl almost successfully - rm fails with ERROR: LoadError: unlink: resource busy or locked (EBUSY) so I commented them out

**Comment by quinnj** [comment]
The last error you saw should now be resolved in the newest set of tests.
