### ISSUE TITLE
Ambiguous definitions 

### ISSUE THREAD

**Issue by lawless-m** [JuliaDB/SQLite.jl#116]
OK, I got SQLite working but I get these warnings every time I use it

`
julia> using SQLite
WARNING: New definition
    promote_op(Type{#T<:Any}, Any) at C:\Users\lesslaw\.julia\v0.4\NullableArrays\src\operators.jl:10
is ambiguous with:
    promote_op(Any, Type{#R<:Number}) at C:\Users\lesslaw\.julia\v0.4\NullableArrays\src\operators.jl:12.
To fix, define
    promote_op(Type{#T<:Any}, Type{#R<:Number})
before the new definition.
WARNING: Method definition convert(Type{Array{#T<:Any, #n<:Any}}, AbstractArray{#S<:Any, #n<:Any}) in module Base at array.jl:241 overwritten in module CategoricalArrays at C:\Users\lesslaw\.julia\v0.4\CategoricalArrays\src\CategoricalArrays.jl:19.
WARNING: Method definition convert(Type{Array{#T<:Any, N<:Any}}, AbstractArray{#S<:Any, #n<:Any}) in module Base at array.jl:240 overwritten in module CategoricalArrays at C:\Users\lesslaw\.julia\v0.4\CategoricalArrays\src\CategoricalArrays.jl:18.
WARNING: Method definition convert(Type{Base.Nullable{T<:Any}}, #T<:Any) in module Base at nullable.jl:19 overwritten in module CategoricalArrays at C:\Users\lesslaw\.julia\v0.4\CategoricalArrays\src\CategoricalArrays.jl:21.
WARNING: New definition
    convert(Type{CategoricalArrays.NominalPool{#S<:Any, #R<:Any, V<:Any}}, CategoricalArrays.NominalPool) at C:\Users\lesslaw\.julia\v0.4\CategoricalArrays\src\pool.jl:54
is ambiguous with:
    convert(Type{CategoricalArrays.NominalPool{#T<:Any, #R<:Any, V<:Any}}, CategoricalArrays.NominalPool{#T<:Any, #R<:Any, V<:Any}) at C:\Users\lesslaw\.julia\v0.4\CategoricalArrays\src\pool.jl:51.
To fix, define
    convert(Type{CategoricalArrays.NominalPool{#S<:Any, #R<:Any, V<:Any}}, CategoricalArrays.NominalPool{#S<:Any, _<:Integer, V<:Any})
before the new definition.
WARNING: New definition
    convert(Type{CategoricalArrays.OrdinalPool{#S<:Any, #R<:Any, V<:Any}}, CategoricalArrays.OrdinalPool) at C:\Users\lesslaw\.julia\v0.4\CategoricalArrays\src\pool.jl:54
is ambiguous with:
    convert(Type{CategoricalArrays.OrdinalPool{#T<:Any, #R<:Any, V<:Any}}, CategoricalArrays.OrdinalPool{#T<:Any, #R<:Any, V<:Any}) at C:\Users\lesslaw\.julia\v0.4\CategoricalArrays\src\pool.jl:51.
To fix, define
    convert(Type{CategoricalArrays.OrdinalPool{#S<:Any, #R<:Any, V<:Any}}, CategoricalArrays.OrdinalPool{#S<:Any, _<:Integer, V<:Any})
before the new definition.
WARNING: New definition
    convert(Type{#S<:Any}, CategoricalArrays.CategoricalValue{#T<:Any, R<:Integer}) at C:\Users\lesslaw\.julia\v0.4\CategoricalArrays\src\value.jl:28
is ambiguous with:
    convert(Type{Base.Nullable{#T<:Any}}, #T<:Any) at nullable.jl:18.
To fix, define
    convert(Type{Base.Nullable{_<:CategoricalArrays.CategoricalValue{#T<:Any, R<:Integer}}}, _<:CategoricalArrays.CategoricalValue{#T<:Any, R<:Integer})
before the new definition.
WARNING: New definition
    convert(Type{CategoricalArrays.NominalArray{#T<:Any, #N<:Any, #R<:Any}}, CategoricalArrays.NominalArray) at C:\Users\lesslaw\.julia\v0.4\CategoricalArrays\src\array.jl:97
is ambiguous with:
    convert(Type{CategoricalArrays.NominalArray{#T<:Any, #N<:Any, #R<:Any}}, CategoricalArrays.NominalArray{#T<:Any, #N<:Any, #R<:Any}) at C:\Users\lesslaw\.julia\v0.4\CategoricalArrays\src\array.jl:56.
To fix, define
    convert(Type{CategoricalArrays.NominalArray{#T<:Any, #N<:Any, #R<:Any}}, CategoricalArrays.NominalArray{#T<:Any, #N<:Any, _<:Integer})
before the new definition.
WARNING: New definition
    convert(Type{CategoricalArrays.OrdinalArray{#T<:Any, #N<:Any, #R<:Any}}, CategoricalArrays.OrdinalArray) at C:\Users\lesslaw\.julia\v0.4\CategoricalArrays\src\array.jl:97
is ambiguous with:
    convert(Type{CategoricalArrays.OrdinalArray{#T<:Any, #N<:Any, #R<:Any}}, CategoricalArrays.OrdinalArray{#T<:Any, #N<:Any, #R<:Any}) at C:\Users\lesslaw\.julia\v0.4\CategoricalArrays\src\array.jl:56.
To fix, define
    convert(Type{CategoricalArrays.OrdinalArray{#T<:Any, #N<:Any, #R<:Any}}, CategoricalArrays.OrdinalArray{#T<:Any, #N<:Any, _<:Integer})
before the new definition.
WARNING: New definition
    convert(Type{CategoricalArrays.NullableNominalArray{#T<:Any, #N<:Any, #R<:Any}}, CategoricalArrays.NullableNominalArray) at C:\Users\lesslaw\.julia\v0.4\CategoricalArrays\src\array.jl:97
is ambiguous with:
    convert(Type{CategoricalArrays.NullableNominalArray{#T<:Any, #N<:Any, #R<:Any}}, CategoricalArrays.NullableNominalArray{#T<:Any, #N<:Any, #R<:Any}) at C:\Users\lesslaw\.julia\v0.4\CategoricalArrays\src\array.jl:56.
To fix, define
    convert(Type{CategoricalArrays.NullableNominalArray{#T<:Any, #N<:Any, #R<:Any}}, CategoricalArrays.NullableNominalArray{#T<:Any, #N<:Any, _<:Integer})
before the new definition.
WARNING: New definition
    convert(Type{CategoricalArrays.NullableOrdinalArray{#T<:Any, #N<:Any, #R<:Any}}, CategoricalArrays.NullableOrdinalArray) at C:\Users\lesslaw\.julia\v0.4\CategoricalArrays\src\array.jl:97
is ambiguous with:
    convert(Type{CategoricalArrays.NullableOrdinalArray{#T<:Any, #N<:Any, #R<:Any}}, CategoricalArrays.NullableOrdinalArray{#T<:Any, #N<:Any, #R<:Any}) at C:\Users\lesslaw\.julia\v0.4\CategoricalArrays\src\array.jl:56.
To fix, define
    convert(Type{CategoricalArrays.NullableOrdinalArray{#T<:Any, #N<:Any, #R<:Any}}, CategoricalArrays.NullableOrdinalArray{#T<:Any, #N<:Any, _<:Integer})
before the new definition.
WARNING: New definition
    promote_rule(Type{#T<:Any}, Type{DataArrays.NAtype}) at C:\Users\lesslaw\.julia\v0.4\DataArrays\src\natype.jl:37
is ambiguous with:
    promote_rule(Type{CategoricalArrays.NominalValue{#S<:Any, R<:Integer}}, Type{#T<:Any}) at C:\Users\lesslaw\.julia\v0.4\CategoricalArrays\src\value.jl:12.
To fix, define
    promote_rule(Type{CategoricalArrays.NominalValue{#S<:Any, R<:Integer}}, Type{DataArrays.NAtype})
before the new definition.
WARNING: New definition
    promote_rule(Type{#T<:Any}, Type{DataArrays.NAtype}) at C:\Users\lesslaw\.julia\v0.4\DataArrays\src\natype.jl:37
is ambiguous with:
    promote_rule(Type{CategoricalArrays.NominalValue}, Type{#T<:Any}) at C:\Users\lesslaw\.julia\v0.4\CategoricalArrays\src\value.jl:13.
To fix, define
    promote_rule(Type{CategoricalArrays.NominalValue}, Type{DataArrays.NAtype})
before the new definition.
WARNING: New definition
    promote_rule(Type{#T<:Any}, Type{DataArrays.NAtype}) at C:\Users\lesslaw\.julia\v0.4\DataArrays\src\natype.jl:37
is ambiguous with:
    promote_rule(Type{CategoricalArrays.NominalValue{#S<:Any, #R<:Any}}, Type{#T<:Any}) at C:\Users\lesslaw\.julia\v0.4\CategoricalArrays\src\value.jl:11.
To fix, define
    promote_rule(Type{CategoricalArrays.NominalValue{#S<:Any, #R<:Any}}, Type{DataArrays.NAtype})
before the new definition.
WARNING: New definition
    promote_rule(Type{#T<:Any}, Type{DataArrays.NAtype}) at C:\Users\lesslaw\.julia\v0.4\DataArrays\src\natype.jl:37
is ambiguous with:
    promote_rule(Type{CategoricalArrays.OrdinalValue{#S<:Any, R<:Integer}}, Type{#T<:Any}) at C:\Users\lesslaw\.julia\v0.4\CategoricalArrays\src\value.jl:12.
To fix, define
    promote_rule(Type{CategoricalArrays.OrdinalValue{#S<:Any, R<:Integer}}, Type{DataArrays.NAtype})
before the new definition.
WARNING: New definition
    promote_rule(Type{#T<:Any}, Type{DataArrays.NAtype}) at C:\Users\lesslaw\.julia\v0.4\DataArrays\src\natype.jl:37
is ambiguous with:
    promote_rule(Type{CategoricalArrays.OrdinalValue}, Type{#T<:Any}) at C:\Users\lesslaw\.julia\v0.4\CategoricalArrays\src\value.jl:13.
To fix, define
    promote_rule(Type{CategoricalArrays.OrdinalValue}, Type{DataArrays.NAtype})
before the new definition.
WARNING: New definition
    promote_rule(Type{#T<:Any}, Type{DataArrays.NAtype}) at C:\Users\lesslaw\.julia\v0.4\DataArrays\src\natype.jl:37
is ambiguous with:
    promote_rule(Type{CategoricalArrays.OrdinalValue{#S<:Any, #R<:Any}}, Type{#T<:Any}) at C:\Users\lesslaw\.julia\v0.4\CategoricalArrays\src\value.jl:11.
To fix, define
    promote_rule(Type{CategoricalArrays.OrdinalValue{#S<:Any, #R<:Any}}, Type{DataArrays.NAtype})
before the new definition.
WARNING: New definition
    isequal(DataArrays.NAtype, Any) at C:\Users\lesslaw\.julia\v0.4\DataArrays\src\operators.jl:507
is ambiguous with:
    isequal(Any, CategoricalArrays.CategoricalValue) at C:\Users\lesslaw\.julia\v0.4\CategoricalArrays\src\value.jl:69.
To fix, define
    isequal(DataArrays.NAtype, CategoricalArrays.CategoricalValue)
before the new definition.
WARNING: New definition
    isequal(Any, DataArrays.NAtype) at C:\Users\lesslaw\.julia\v0.4\DataArrays\src\operators.jl:508
is ambiguous with:
    isequal(CategoricalArrays.CategoricalValue, Any) at C:\Users\lesslaw\.julia\v0.4\CategoricalArrays\src\value.jl:68.
To fix, define
    isequal(CategoricalArrays.CategoricalValue, DataArrays.NAtype)
before the new definition.
WARNING: New definition
    broadcast(Function, DataArrays.PooledDataArray...) at C:\Users\lesslaw\.julia\v0.4\DataArrays\src\broadcast.jl:319
is ambiguous with:
    broadcast(Any, NullableArrays.NullableArray...).
To fix, define
    broadcast(Function)
before the new definition.
WARNING: New definition
    ==(DataArrays.NAtype, Any) at C:\Users\lesslaw\.julia\v0.4\DataArrays\src\operators.jl:610
is ambiguous with:
    ==(Any, CategoricalArrays.CategoricalValue) at C:\Users\lesslaw\.julia\v0.4\CategoricalArrays\src\value.jl:64.
To fix, define
    ==(DataArrays.NAtype, CategoricalArrays.CategoricalValue)
before the new definition.
WARNING: New definition
    ==(Any, DataArrays.NAtype) at C:\Users\lesslaw\.julia\v0.4\DataArrays\src\operators.jl:610
is ambiguous with:
    ==(CategoricalArrays.CategoricalValue, Any) at C:\Users\lesslaw\.julia\v0.4\CategoricalArrays\src\value.jl:63.
To fix, define
    ==(CategoricalArrays.CategoricalValue, DataArrays.NAtype)
before the new definition.

`

**Comment by quinnj** [comment]
The newest SQLite release is 0.5 only and avoids this ambiguity warnings (which were from CategoricalArrays package anyway)
