### ISSUE TITLE
 Subsets in DataFrames generated with SQLite

### ISSUE THREAD

**Issue by alvaro1101** [JuliaDB/SQLite.jl#118]
I'm try to get a subsets from a DataFrame generated with SQLite:

```
julia> using DataFrames, SQLite

julia> db = SQLite.DB("Chinook_Sqlite.sqlite")

julia> SQLite.query(db, "SELECT FirstName, LastName FROM Employee;")

julia> df[:FirstName]
8-element NullableArrays.NullableArray{String,1}:
 "Andrew"  
 "Nancy"   
 "Jane"    
 "Margaret"
 "Steve"   
 "Michael" 
 "Robert"  
 "Laura"   

julia> df[:FirstName] .== "Laura"
8-element BitArray{1}:
 false
 false
 false
 false
 false
 false
 false
 false   ## This should be true?
```
I tried in several SQLite query, and I couldn't get any proper masked array.

**Comment by nalimilan** [comment]
That's an issue with `NullableArray`: https://github.com/JuliaStats/NullableArrays.jl/issues/142. We're currently working on it, but it's trickier than it sounds. For now, one approach is:
```julia
isequal.(df[:FirstName], Nullable("Laura"))
```

If you don't have any missing values, it will be simpler to use `dropnull` to convert columns to `Array` one by one.

**Comment by quinnj** [comment]
SQLite no longer uses NullableArrays in DataFrames, just plain Vector{T} or Vector{Union{T, Null}}.
