### ISSUE TITLE
Pkg.test fails

### ISSUE THREAD

**Issue by bhalonen** [JuliaDB/SQLite.jl#129]
I cannot get the SQLite package to work, and the tests are failing.

> julia> Pkg.test("SQLite")
INFO: Computing test dependencies for SQLite...
INFO: Installing DataStreamsIntegrationTests v0.0.2
INFO: Testing SQLite
WARNING: Method definition ==(Base.Nullable{S}, Base.Nullable{T}) in module Base at nullable.jl:238 overwritten in module NullableArrays at /Users/brent/.julia/v0.6/NullableArrays/src/operators.jl:128.
Test Failed
  Expression: typeof(r[1, 5]) == Nullable{Date}
   Evaluated: Nullable{Array{UInt8,1}} == Nullable{Date}
ERROR: LoadError: There was an error during testing
while loading /Users/brent/.julia/v0.6/SQLite/test/runtests.jl, in expression starting on line 56
====================================================================================[ ERROR: SQLite ]=====================================================================================
failed process: Process(`/Applications/Julia-0.6.app/Contents/Resources/julia/bin/julia -Ccore2 -J/Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=yes --compilecache=yes /Users/brent/.julia/v0.6/SQLite/test/runtests.jl`, ProcessExited(1)) [1]
==========================================================================================================================================================================================
INFO: Removing DataStreamsIntegrationTests v0.0.2
ERROR: SQLite had test errors

Julia version:  
`julia> versioninfo()
Julia Version 0.6.0
Commit 903644385b (2017-06-19 13:05 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)`

SQLite version: 
`v"0.4.5"`

**Comment by ignaciomartin** [comment]
In Windows platform test also fails:
```
julia>  Pkg.test("SQLite")
INFO: Computing test dependencies for SQLite...
INFO: Installing DataStreamsIntegrationTests v0.0.2
INFO: Testing SQLite
WARNING: Method definition ==(Base.Nullable{S}, Base.Nullable{T}) in module Base at nullable.jl:238 overwritten in module NullableArrays at D:\Julia\Paquetes\v0.6\NullableArrays\src\operators.jl:128.
Test Failed
  Expression: typeof(r[1, 5]) == Nullable{Date}
   Evaluated: Nullable{Array{UInt8,1}} == Nullable{Date}
ERROR: LoadError: There was an error during testing
while loading D:\Julia\Paquetes\v0.6\SQLite\test\runtests.jl, in expression starting on line 56
================================================================================================[ ERROR: SQLite ]================================================================================================


failed process: Process(`'D:\Usuarios\ignacio.martin\AppData\Local\Julia-0.6.0\bin\julia.exe' -Cx86-64 '-JD:\Usuarios\ignacio.martin\AppData\Local\Julia-0.6.0\lib\julia\sys.dll' --compile=yes --depwarn=yes --c
heck-bounds=yes --code-coverage=none --color=yes --compilecache=yes 'D:\Julia\Paquetes\v0.6\SQLite\test\runtests.jl'`, ProcessExited(1)) [1]

=================================================================================================================================================================================================================

INFO: Removing DataStreamsIntegrationTests v0.0.2
ERROR: SQLite had test errors

julia> versioninfo()
Julia Version 0.6.0
Commit 903644385b* (2017-06-19 13:05 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, ivybridge)

julia>
```

**Comment by quinnj** [comment]
Tests now pass on latest master (plus master of DataFrames).

**Comment by bhalonen** [comment]
Awesome, good work!

**Comment by felipenoris** [comment]
Thank you!
