### ISSUE TITLE
Streaming from CSV to SQLite fails

### ISSUE THREAD

**Issue by ignaciomartin** [JuliaDB/SQLite.jl#130]
I'm trying to test a data stream flow from CSV to SQLite, but I can not. 
This is what I do:

1.- Download a simple CSV file (the RAL colour standard) from this [url ](https://gist.githubusercontent.com/lunohodov/1995178/raw/cb8cf1ebe1d1b8fa5759e287ebd6eaecbe3bc3e4/ral_standard.csv).

2.- Open Julia REPL and  check version and updates:
```
julia> versioninfo()
Julia Version 0.6.0
Commit 903644385b* (2017-06-19 13:05 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, ivybridge)

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Updating SQLite master...
INFO: Computing changes...
INFO: No packages to install, update or remove

julia> Pkg.installed("SQLite")
v"0.4.5+"

julia> Pkg.installed("CSV")
v"0.1.4"  
```
3.- Using required packages:
```
julia> using SQLite, CSV
```
4.- Define a CSV stream source :
```
julia> csv_source = CSV.Source("ral_standard.csv")
CSV.Source: ral_standard.csv
    CSV.Options:
        delim: ','
        quotechar: '"'
        escapechar: '\\'
        null: ""
        dateformat: dateformat"yyyy-mm-dd"
Data.Schema{true}:
rows: 213       cols: 9
Columns:
 "RAL"          Nullable{WeakRefString{UInt8}}
 " RGB"         Nullable{WeakRefString{UInt8}}
 " HEX"         Nullable{WeakRefString{UInt8}}
 " German"      Nullable{WeakRefString{UInt8}}
 " English"     Nullable{WeakRefString{UInt8}}
 " French"      Nullable{WeakRefString{UInt8}}
 " Spanish"     Nullable{WeakRefString{UInt8}}
 " Italian"     Nullable{WeakRefString{UInt8}}
 " Nederlands"  Nullable{WeakRefString{UInt8}}
```

5.- Create/open a SQLite database:
```
julia> db = SQLite.DB("FromCSV.db3")
SQLite.DB("FromCSV.db3")
```

6.- Define a "source-based" schema:
```
julia> schema = Data.schema(csv_source)
Data.Schema{true}:
rows: 213       cols: 9
Columns:
 "RAL"          Nullable{WeakRefString{UInt8}}
 " RGB"         Nullable{WeakRefString{UInt8}}
 " HEX"         Nullable{WeakRefString{UInt8}}
 " German"      Nullable{WeakRefString{UInt8}}
 " English"     Nullable{WeakRefString{UInt8}}
 " French"      Nullable{WeakRefString{UInt8}}
 " Spanish"     Nullable{WeakRefString{UInt8}}
 " Italian"     Nullable{WeakRefString{UInt8}}
 " Nederlands"  Nullable{WeakRefString{UInt8}}
```

7.- Define a SQLite Sink using previous schema:
```
julia> sqlite_sink = SQLite.Sink(db, "mycolors", schema)
SQLite.Sink(SQLite.DB("FromCSV.db3"), "mycolors", SQLite.Stmt(SQLite.DB("FromCSV.db3"), Ptr{Void} @0x00000000225cb530), "")
```
It is now possible to externally verify that the table has been succesfull created:
![image](https://user-images.githubusercontent.com/19220563/29124354-ff166cd6-7d18-11e7-81ef-ed1044a5c3e9.png)

8.- Stream data flow from CSV to SQLite and close streaming channel:
```
julia> Data.stream!(csv_source, sqlite_sink)
SQLite.Sink(SQLite.DB("FromCSV.db3"), "mycolors", SQLite.Stmt(SQLite.DB("FromCSV.db3"), Ptr{Void} @0x00000000225cb530), "SQLITEiw5wTXq8nP")
julia> Data.close!(sqlite_sink)
```
If I now try to externally check the table, I can see that the table has been filled with the same number of rows as the CSV file, but they are all empty!:
![image](https://user-images.githubusercontent.com/19220563/29125002-cd294462-7d1a-11e7-8692-3abb2029a8e5.png)

Am I doing something wrong, or is it a bug?

**Comment by quinnj** [comment]
Hey @ignaciomartin, sorry for the slow response here; at first, I thought there might be a more complicated bug underneath, but after digging in here, it's actually a pretty simple fix. The only think you're missing here is to call `Data.close!(sqlite_sink)`. When you open an `SQLite.Sink`, it starts a "transaction", and any number of `Data.stream!` calls can be made, but no data will be "committed" until `Data.close!(sink)` is called to commit the transaction. Sorry for the hassle here. The DataStreams docs have recently been vastly upgraded and hopefully it's more clear that sinks are not necessarily required to "commit" streamed data until `Data.close!` is called.

Alternatively, you may find it easier to use the provided convenience function
```julia
SQLite.load(db, "mycolors", csv_source)
```
In this form, `SQLite.load` will construct the `SQLite.Sink` for you, `Data.stream!` the data, and call `Data.close!` to commit the results, all in one function call.

**Comment by ignaciomartin** [comment]
Hey @quinnj. Thanks for your reply.

> The only think you're missing here is to call Data.close!(sqlite_sink)

I'm sorry, but if you check the second REPL command, in step 8, you will see that this function was  called certainly.

It could be a source -> sink type mismatch problem, I think.

The first five lines of Sink.jl source file, translates the CSV source types to SQLite types:

```
sqlitetype{T<:Integer}(::Type{T}) = "INT"
sqlitetype{T<:AbstractFloat}(::Type{T}) = "REAL"
sqlitetype{T<:AbstractString}(::Type{T}) = "TEXT"
sqlitetype(::Type{NullType}) = "NULL"
sqlitetype(x) = "BLOB"
```

None of types that have returned the CSV schema (only this really: Nullable{WeakRefString{UInt8}}) is provided in Sink.jl.
```
Columns:
 "RAL"          Nullable{WeakRefString{UInt8}}
 " RGB"         Nullable{WeakRefString{UInt8}}
 " HEX"         Nullable{WeakRefString{UInt8}}
 " German"      Nullable{WeakRefString{UInt8}}
 " English"     Nullable{WeakRefString{UInt8}}
 " French"      Nullable{WeakRefString{UInt8}}
 " Spanish"     Nullable{WeakRefString{UInt8}}
 " Italian"     Nullable{WeakRefString{UInt8}}
 " Nederlands"  Nullable{WeakRefString{UInt8}}
```

 So all fields are "translated" as "BLOB" and data can not be stored in the SQLite table therefore.
 
A solution  could be to manually define a schema with types that Sink.jl can handle properly:
 ```
 schema = Data.Schema(["RAL", "RBG", "HEX", "German", "English", "French", 
        "Spanish", "Italian", "Nederlands"],
    [AbstractString, AbstractString, AbstractString, AbstractString, AbstractString,
        AbstractString, AbstractString, AbstractString, AbstractString])
 ```
 Records are now sent successfully, but unfortunately CSV -> SQLite automation is lost.
 
The new SQLIte.load() function is very interesting, but neither is it able to translate this types properly.
