### ISSUE TITLE
How to close a database connection?

### ISSUE THREAD

**Issue by alxfed** [JuliaDB/SQLite.jl#132]
I'm sorry for asking this stupid question here, but... 
where is the 'close(db)' function of something to that effect?
I'm implementing an application that needs to open/close/reopen multiple connections with separate SQLite db files (like tens of them), I can not just abandon the previous connection...

**Comment by alxfed** [comment]
Found other ways to do it ( three to be precise). Thank you.

**Comment by Omazaria** [comment]
Can you communicate how do you do that please?

**Comment by rapus95** [comment]
I'd be curious aswell since I too often get stuck in "Database is locked" errors.

**Comment by quinnj** [comment]
You can call `SQLite._close(db)` for now; I can probably clean things up and implement an official `close(db)` that will be safe and idempotent.
