### ISSUE TITLE
Do custom types persist? 

### ISSUE THREAD

**Issue by yakir12** [JuliaDB/SQLite.jl#133]
Thank you for this great package!
I'm unclear on if we can keep custom types in the database? I imagine nulls are a problem, but did the consensus on how to deal with them cascade here, or how is this dealt with? Thanks in advance!

**Comment by quinnj** [comment]
Yes, you can store custom types. Currently they rely on the `serialize` and `deserialize` functions from Base, and thus don't have a guarantee of working across julia minor versions (indeed, there were breaking `serialize` changes from 0.5 => 0.6, and 0.6 => 0.7). Nulls (now `missing::Missing`) are handled specially and stored as sqlite `null` values.
