### ISSUE TITLE
Lots of depreciation warnings in 0.4.0

### ISSUE THREAD

**Issue by amellnik** [JuliaDB/SQLite.jl#75]
Posting here for easy tracking, I will try to take a look at these when I can since it sounds like low-hanging fruit.

    using SQLite

produces
    
    WARNING: Base.Uint8 is deprecated, use UInt8 instead.
    likely near C:\Users\amellnik\.julia\v0.4\SQLite\src\show.jl:33
    ....
    WARNING: Base.FloatingPoint is deprecated, use AbstractFloat instead.
    likely near C:\Users\amellnik\.julia\v0.4\SQLite\src\SQLite.jl:139
    WARNING: Base.String is deprecated, use AbstractString instead.
    likely near C:\Users\amellnik\.julia\v0.4\SQLite\src\SQLite.jl:244

and 

    db = SQLiteDB("test.sqlite")

produces 

    WARNING: Base.Uint16 is deprecated, use UInt16 instead.
      likely near In[2]:1
    ....
    WARNING: Base.Nothing is deprecated, use Void instead.
      likely near In[2]:1
    ....     
    in __register#31__ at C:\Users\amellnik\.julia\v0.4\SQLite\src\UDF.jl:198
    WARNING: Base.Nothing is deprecated, use Void instead.

**Comment by Sean1708** [comment]
@amellnik I've just merged #73 into `master`, could you check whether that fixes everything please? You can pull the `master` branch using `Pkg.checkout`:

```julia
julia> Pkg.checkout("SQLite")
```

@quinnj we should probably tag a new release now that v0.4's out. Do you want to wait until your latest updates have landed or will they not be ready in time?

**Comment by quinnj** [comment]
@Sean1708, let's tag a new release. Once I get the other updates ready, we can tag again.

**Comment by amellnik** [comment]
I no longer get any warnings on the current master.  Nicely done!

**Comment by Sean1708** [comment]
Sounds good, I'll tag as v0.2.1 tomorrow morning.

**Comment by Sean1708** [comment]
All done.
