### ISSUE TITLE
some changes from working jq/updates branch

### ISSUE THREAD

**Issue by getzdan** [JuliaDB/SQLite.jl#78]
just added a pull request from a branch dg/testing forked from @quinnj branch jq/updates.
it is broken to many small commits. these include a bugfix; an addition of close() functions instead of finalizers - this is important since, for example, the DB cannot be closed before Stmt handlers are finalized and the finalization timing and order are not guaranteed (better allow users to civilly release resources) ; and more such tidbit changes. related pull request: #77

**Comment by Sean1708** [comment]
Github's pull requests are treated pretty much the same way as issues so you only have to open one or the other, if you open a pull request _and_ an issue it can fragment discussion. For that reason I'm gonna close this issue.
