### ISSUE TITLE
using SQLite makes Julia crash 0.4.0 Win7

### ISSUE THREAD

**Issue by kafisatz** [JuliaDB/SQLite.jl#81]
Hi Jacob 

Pkg.status show the versions (does it not?).
I only executed the three lines below:

Pkg.add("SQLite")
Pkg.status()
using SQLite  # after this julia crashes!

As a side note: the log below shows that the deps\build.jl file still has the old Dict notation in a few places.

Executing .juliarc.jl... done
INFO: Installing CSV v0.0.2
INFO: Installing DataStreams v0.0.2
INFO: Installing NullableArrays v0.0.2
INFO: Installing SQLite v0.2.2
INFO: Building WinRPM
INFO: Downloading https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUS
E_13.2/repodata/repomd.xml
INFO: Downloading https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUS
E_13.2/repodata/repomd.xml
INFO: Building SQLite

WARNING: deprecated syntax "{a=>b, ...}" at C:\Users\workstation\.julia\SQLite\deps\build.jl:17.
Use "Dict{Any,Any}(a=>b, ...)" instead.

WARNING: deprecated syntax "{a=>b, ...}" at C:\Users\workstation\.julia\SQLite\deps\build.jl:18.
Use "Dict{Any,Any}(a=>b, ...)" instead.

WARNING: deprecated syntax "[a=>b, ...]" at C:\Users\workstation\.julia\SQLite\deps\build.jl:21.
Use "Dict(a=>b, ...)" instead.
INFO: Updating WinRPM package list
INFO: Downloading https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUS
E_13.2/repodata/repomd.xml
INFO: Downloading https://cache.e.ip.saba.us/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUS
E_13.2/repodata/repomd.xml
INFO: Package database updated
27 required packages:
 - Coverage                      0.2.3
 - DataFrames                    0.6.10
 - Dates                         0.4.4
 - FastAnonymous                 0.3.2
 - Gadfly                        0.3.18
 - Graphics                      0.1.3
 - HDF5                          0.5.6
 - Iterators                     0.1.9
 - JLD                           0.5.5
 - JSON                          0.5.0
 - Jewel                         1.0.7
 - Libz                          0.0.2
 - Lint                          0.1.68
 - Loess                         0.0.5
 - Mocha                         0.1.0
 - NumericExtensions             0.6.2
 - ODBC                          0.3.10
 - ProfileView                   0.1.1
 - ProgressMeter                 0.2.1
 - PyCall                        1.1.2
 - RDatasets                     0.1.2
 - SQLite                        0.2.2
 - SortingAlgorithms             0.0.6
 - StatsBase                     0.7.4
 - TypeCheck                     0.0.3
 - WinRPM                        0.1.13
 - ZipFile                       0.2.5
56 additional packages:
 - ArrayViews                    0.6.4
 - BinDeps                       0.3.18
 - Blosc                         0.1.4
 - BufferedStreams               0.0.2
 - CSV                           0.0.2
 - Cairo                         0.2.31
 - Calculus                      0.1.13
 - Codecs                        0.1.5
 - ColorTypes                    0.1.7
 - Colors                        0.5.4
 - Compat                        0.7.7
 - Compose                       0.3.18
 - Conda                         0.1.7
 - Contour                       0.0.8
 - DataArrays                    0.2.19
 - DataStreams                   0.0.2
 - DataStructures                0.3.13
 - Debug                         0.1.6
 - Distances                     0.2.1
 - Distributions                 0.8.7
 - Docile                        0.5.19
 - DualNumbers                   0.1.5
 - FactCheck                     0.4.1
 - FixedPointNumbers             0.0.12
 - GZip                          0.2.18
 - Grid                          0.4.0
 - Gtk                           0.9.2
 - GtkUtilities                  0.0.6
 - Hexagons                      0.0.4
 - HttpCommon                    0.2.4
 - HttpParser                    0.1.1
 - ImmutableArrays               0.0.11
 - JuliaParser                   0.6.3
 - KernelDensity                 0.1.2
 - LNR                           0.0.1
 - Lazy                          0.10.1
 - LibExpat                      0.1.0
 - Logging                       0.1.1
 - MacroTools                    0.2.0
 - MbedTLS                       0.1.4
 - MySQL                         0.0.0-             master (unregistered)
 - NaNMath                       0.1.1
 - NullableArrays                0.0.2
 - NumericFuns                   0.2.4
 - Optim                         0.4.4
 - PDMats                        0.3.6
 - Reexport                      0.0.3
 - Requests                      0.3.2
 - Requires                      0.2.1
 - SHA                           0.1.2
 - Showoff                       0.0.6
 - StatsFuns                     0.2.0
 - URIParser                     0.1.1
 - WoodburyMatrices              0.1.2
 - Zlib                          0.1.12
 - lib                           0.0.0-             non-repo (unregistered)

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety
). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x64f749d2 -- jl_deserialize_lambdas_from_mod at C:\Program Files\Juno\reso
urces\app\julia\bin\libjulia.dll (unknown line)
jl_deserialize_lambdas_from_mod at C:\Program Files\Juno\resources\app\julia\bin\libjulia.dll (unknown line)
jl_deserialize_lambdas_from_mod at C:\Program Files\Juno\resources\app\julia\bin\libjulia.dll (unknown line)
jl_restore_incremental at C:\Program Files\Juno\resources\app\julia\bin\libjulia.dll (unknown line)
_require_from_serialized at loading.jl:84
jlcall__require_from_serialized_1832 at  (unknown line)
jl_apply_generic at C:\Program Files\Juno\resources\app\julia\bin\libjulia.dll (unknown line)
_require_from_serialized at loading.jl:109
require at loading.jl:219
jlcall_require_1762 at  (unknown line)
jl_apply_generic at C:\Program Files\Juno\resources\app\julia\bin\libjulia.dll (unknown line)
jl_init_serializer at C:\Program Files\Juno\resources\app\julia\bin\libjulia.dll (unknown line)
jl_eval_with_compiler_p at C:\Program Files\Juno\resources\app\julia\bin\libjulia.dll (unknown line)
jl_eval_module_expr at C:\Program Files\Juno\resources\app\julia\bin\libjulia.dll (unknown line)
jl_eval_with_compiler_p at C:\Program Files\Juno\resources\app\julia\bin\libjulia.dll (unknown line)
jl_eval_module_expr at C:\Program Files\Juno\resources\app\julia\bin\libjulia.dll (unknown line)
jl_eval_with_compiler_p at C:\Program Files\Juno\resources\app\julia\bin\libjulia.dll (unknown line)
jl_eval_with_compiler_p at C:\Program Files\Juno\resources\app\julia\bin\libjulia.dll (unknown line)
jl_parse_eval_all at C:\Program Files\Juno\resources\app\julia\bin\libjulia.dll (unknown line)
jl_load_ at C:\Program Files\Juno\resources\app\julia\bin\libjulia.dll (unknown line)
include at boot.jl:261
jl_apply_generic at C:\Program Files\Juno\resources\app\julia\bin\libjulia.dll (unknown line)
include_from_node1 at loading.jl:304
jl_apply_generic at C:\Program Files\Juno\resources\app\julia\bin\libjulia.dll (unknown line)
jl_interpret_toplevel_expr at C:\Program Files\Juno\resources\app\julia\bin\libjulia.dll (unknown line)
jl_interpret_toplevel_thunk_with at C:\Program Files\Juno\resources\app\julia\bin\libjulia.dll (unknown line)
jl_eval_with_compiler_p at C:\Program Files\Juno\resources\app\julia\bin\libjulia.dll (unknown line)
jl_f_tuple at C:\Program Files\Juno\resources\app\julia\bin\libjulia.dll (unknown line)
require at loading.jl:243
jlcall_require_1762 at  (unknown line)
jl_apply_generic at C:\Program Files\Juno\resources\app\julia\bin\libjulia.dll (unknown line)
jl_init_serializer at C:\Program Files\Juno\resources\app\julia\bin\libjulia.dll (unknown line)
jl_eval_with_compiler_p at C:\Program Files\Juno\resources\app\julia\bin\libjulia.dll (unknown line)
jl_parse_eval_all at C:\Program Files\Juno\resources\app\julia\bin\libjulia.dll (unknown line)
jl_load_ at C:\Program Files\Juno\resources\app\julia\bin\libjulia.dll (unknown line)
include at boot.jl:261
jl_apply_generic at C:\Program Files\Juno\resources\app\julia\bin\libjulia.dll (unknown line)
include_from_node1 at loading.jl:304
jl_apply_generic at C:\Program Files\Juno\resources\app\julia\bin\libjulia.dll (unknown line)
jl_interpret_toplevel_expr at C:\Program Files\Juno\resources\app\julia\bin\libjulia.dll (unknown line)
jl_interpret_toplevel_thunk_with at C:\Program Files\Juno\resources\app\julia\bin\libjulia.dll (unknown line)
jl_eval_with_compiler_p at C:\Program Files\Juno\resources\app\julia\bin\libjulia.dll (unknown line)
jl_f_tuple at C:\Program Files\Juno\resources\app\julia\bin\libjulia.dll (unknown line)
require at loading.jl:243
jlcall_require_1762 at  (unknown line)
jl_apply_generic at C:\Program Files\Juno\resources\app\julia\bin\libjulia.dll (unknown line)
jl_init_serializer at C:\Program Files\Juno\resources\app\julia\bin\libjulia.dll (unknown line)
jl_eval_with_compiler_p at C:\Program Files\Juno\resources\app\julia\bin\libjulia.dll (unknown line)
jl_parse_eval_all at C:\Program Files\Juno\resources\app\julia\bin\libjulia.dll (unknown line)
jl_load_ at C:\Program Files\Juno\resources\app\julia\bin\libjulia.dll (unknown line)
include at boot.jl:261
jl_apply_generic at C:\Program Files\Juno\resources\app\julia\bin\libjulia.dll (unknown line)
include_from_node1 at loading.jl:304
jl_apply_generic at C:\Program Files\Juno\resources\app\julia\bin\libjulia.dll (unknown line)
process_options at client.jl:308
_start at client.jl:411
jlcall__start_510 at  (unknown line)
jl_apply_generic at C:\Program Files\Juno\resources\app\julia\bin\libjulia.dll (unknown line)
unknown function (ip: 00000000004018D0)
unknown function (ip: 000000000040282B)
unknown function (ip: 000000000040140C)
unknown function (ip: 000000000040153B)
BaseThreadInitThunk at C:\Windows\system32\kernel32.dll (unknown line)
RtlUserThreadStart at C:\Windows\SYSTEM32\ntdll.dll (unknown line)

**Comment by kafisatz** [comment]
I noticed that the package is working on another machine.
Then again I have more than 1 computer where it is not working.

As long as I am the only one with issues, feel free to close this.

**Comment by quinnj** [comment]
No, let's dig into a bit more. I saw this only when there was precompilation involved. Can you post what you show in `~/.julia/lib/v0.4/`?

**Comment by kafisatz** [comment]
I am out of office now. I can do so tomorrow. Maybe deleting all .ji files could solve this (that would force recompilation right?)

**Comment by kafisatz** [comment]
After deleting all ji files things are working again. SQLite tests pass.
Below you find the content of the lib dir prior to deleting the files.
Thank you!


C:\Users\workstation\.julia\lib\v0.4>dir
 Volume in drive C has no label.
 Volume Serial Number is 346B-EEE1

 Directory of C:\Users\workstation\.julia\lib\v0.4

27/10/2015  16:27    <DIR>          .
27/10/2015  16:27    <DIR>          ..
21/10/2015  11:49           176'324 ArrayViews.ji
21/10/2015  11:48            31'527 Blosc.ji
19/10/2015  15:06           127'847 Cairo.ji
19/10/2015  15:06           410'430 Colors.ji
19/10/2015  15:06           421'118 ColorTypes.ji
21/10/2015  11:48            43'654 Compat.ji
27/10/2015  10:12         1'104'667 DataArrays.ji
27/10/2015  10:12           998'267 DataFrames.ji
27/10/2015  16:27         1'303'119 DecisionTreesModule.ji
21/10/2015  11:48           278'137 Docile.ji
19/10/2015  15:06            87'107 FixedPointNumbers.ji
19/10/2015  15:06            37'015 Graphics.ji
19/10/2015  15:06         2'275'500 Gtk.ji
19/10/2015  15:06           124'843 GtkUtilities.ji
21/10/2015  11:49            39'811 GZip.ji
21/10/2015  11:48           380'103 HDF5.ji
21/10/2015  11:49            73'862 Iterators.ji
21/10/2015  11:48           209'276 JLD.ji
14/10/2015  07:39            57'173 JSON.ji
27/10/2015  15:22           126'773 MySQL.ji
27/10/2015  10:44           234'335 NullableArrays.ji
19/10/2015  15:06            80'256 ProfileView.ji
19/10/2015  15:06            17'337 ProfileViewGtk.ji
21/10/2015  11:49            40'279 ProgressMeter.ji
21/10/2015  11:50           603'253 PyCall.ji
09/10/2015  15:51             3'899 Reexport.ji
27/10/2015  07:14            50'199 SHA.ji
21/10/2015  11:49            51'049 SortingAlgorithms.ji
27/10/2015  10:11           434'815 StatsBase.ji
27/10/2015  10:11           262'625 StatsFuns.ji
09/10/2015  15:50            33'762 Totalsizeof.ji
20/10/2015  10:52            93'777 URIParser.ji
              32 File(s)     10'212'139 bytes
               2 Dir(s)  33'696'174'080 bytes free

C:\Users\workstation\.julia\lib\v0.4>

**Comment by quinnj** [comment]
Yeah, the issue was the attempted precompile of NullableArrays.jl. Once that package is precompilable, the rest of the DataStreams/CSV/SQLite packages will be able to precompile
