### ISSUE TITLE
Re-tag as v0.3.0

### ISSUE THREAD

**Issue by tkelman** [JuliaDB/SQLite.jl#83]
ref https://github.com/JuliaLang/METADATA.jl/pull/3881

Dropping Julia 0.3 support necessitates a new minor package version, otherwise it becomes needlessly difficult to ever make a branch and future bugfix release that does support 0.3.

**Comment by quinnj** [comment]
Should I delete the 0.2.2 tag along with tagging 0.3?

**Comment by tkelman** [comment]
No, it's okay to leave as is. As long as future julia-0.4-only tags are only done in the SQLite.jl 0.3.x series, then a future julia-0.3-bugfix tag could be made as SQLite.jl 0.2.3 and it would work fine. The tags would be slightly out of order in terms of content, but that's not really important.

**Comment by quinnj** [comment]
Done.
