### ISSUE TITLE
LoadError: too many parameters for type PointerString

### ISSUE THREAD

**Issue by Ph0non** [JuliaDB/SQLite.jl#84]
On the first try to load SQLite with `using SQLite` julia (0.5, latest master) returns ```LoadError: too many parameters for type PointerString
[...]
while loading [...] SQLite/src/SQLite.jl in expression starting on line 129```

On a second try it works.

**Comment by felipenoris** [comment]
Please, try running 
```julia
julia> Pkg.checkout("DataStreams")
```
and it should be solved.
DataStreams package needs tagging.

**Comment by quinnj** [comment]
Done: https://github.com/JuliaLang/METADATA.jl/pull/4024
