### ISSUE TITLE
query has no method for ::SQLite.DB

### ISSUE THREAD

**Issue by Ph0non** [JuliaDB/SQLite.jl#85]
```
db = SQLite.DB("foo.sqlite")
query(db, "select * from bar")
Error: MethodError: query has no method matching query(::SQLite.DB, ::ASCIIString)
Closest candidates are:
 query(::SQLite.SQLiteDB(T<:AbstractString), ::AbstractString)
 query(::SQLite.SQLiteDB(T<:AbstractString), ::AbstractString, Any)
```

I'm not sure, but maybe this could have the same origin as https://github.com/JuliaDB/SQLite.jl/issues/84

**Comment by felipenoris** [comment]
@Ph0non , also try 
```julia
julia> Pkg.checkout("SQLite")
```
if checking out DataStreams doesn´t do the job.

**Comment by quinnj** [comment]
This is actually by design for the moment to ensure backwards compatibility with 0.3, though I can't remember exactly why at the moment.

**Comment by felipenoris** [comment]
Since both `DataStreams` and `SQLite` packages were updated today on `METADATA`, I can´t reproduce this error after doing a `Pkg.update()` on vertion 0.4.2-pre.

**Comment by Ph0non** [comment]
Same for me.
