### ISSUE TITLE
how to insert Array{Any,2} to a table of database at a time?

### ISSUE THREAD

**Issue by songroom** [JuliaDB/SQLite.jl#87]
now i can use query to insert Array{Any,1} to a table of database.

but how to insert Array{Any,2} at a time or rapidly?

in Array{Any,2}  => out Data.Table ?

thank you!

**Comment by Sean1708** [comment]
Sorry it's taken a while to get back to you, I can't say that I've completely wrapped my head around the new DataStreams interface but I'll give it a shot.

First I'll set up a mock database and some mock data:

```julia
julia> using SQLite

julia> data = Any[11 12 13 14 15
                  21 22 23 24 25
                  31 32 33 34 35
                  41 42 43 44 45]
4x5 Array{Any,2}:
 11  12  13  14  15
 21  22  23  24  25
 31  32  33  34  35
 41  42  43  44  45

julia> db = SQLite.DB()
SQLite.DB(in-memory)
```

Then we define the schema for our table (the first array is column names, the second is column types) and turn our database into a sink (this creates the table if it doesn't already exist):

```julia
julia> schema = Data.Schema(
           ["a", "b", "c", "d", "e"],
           [Int, Int, Int, Int, Int],
       )
0x5 Data.Schema:
a, Int64
b, Int64
c, Int64
d, Int64
e, Int64

julia> sink = SQLite.Sink(schema, db, "my_table")
SQLite.Sink(0x5 Data.Schema:
a, Int64
b, Int64
c, Int64
d, Int64
e, Int64
,SQLite.DB(in-memory),"my_table",SQLite.Stmt(SQLite.DB(in-memory),Ptr{Void} @0x00007fa9b4a3d1e0))
```

Then we turn our data into a source:

```julia
julia> source = Data.Table(data)
Data.Table:
4x5 Data.Schema:
 Column1, Column2, Column3, Column4, Column5
   Int64,   Int64,   Int64,   Int64,   Int64
NullableArrays.NullableArray{T,1}[NullableArrays.NullableArray{Int64,1}[11,21,31,41],NullableArrays.NullableArray{Int64,1}[12,22,32,42],NullableArrays.NullableArray{Int64,1}[13,23,33,43],NullableArrays.NullableArray{Int64,1}[14,24,34,44],NullableArrays.NullableArray{Int64,1}[15,25,35,45]]
```

And finally we stream our data from our source to our sink:

```julia
julia> Data.stream!(source, sink)
SQLite.Sink(0x5 Data.Schema:
a, Int64
b, Int64
c, Int64
d, Int64
e, Int64
,SQLite.DB(in-memory),"my_table",SQLite.Stmt(SQLite.DB(in-memory),Ptr{Void} @0x00007fa9b4a3d1e0))
```

The database will now have a table called `my_table` with 5 integer columns filled with the data.

**Comment by songroom** [comment]
thank you very much!

**Comment by quinnj** [comment]
Thanks for taking this @Sean1708. I've been out of commission the last 2 weeks, so I appreciate the support.
