### ISSUE TITLE
Use declared column type?

### ISSUE THREAD

**Issue by simonbyrne** [JuliaDB/SQLite.jl#92]
The current code for looking up column type uses `sqlite3_column_type`, which just looks at the type of the first element: if this is null then we don't have any type information (e.g. the `ReportsTo` column in the `Employee` table in the test database).

SQLite also provides `sqlite3_column_decltype`: this is a bit less flexible, but could be used as a fallback in this case? (I think this is what RSQLite does).

**Comment by felipenoris** [comment]
Yes. I had this issue with RSQLite when I declared a column as NUMERIC.
I changed that to REAL and it solved de problem: the column returned a floating value even if the first element was an integer.
That was my specific case, maybe not yours.

**Comment by simonbyrne** [comment]
SQLAlchemy [queries `PRAGMA table_info`](https://github.com/zzzeek/sqlalchemy/blob/9d08c6abc21dcf3d832897d38aaba84aeaa14fa6/lib/sqlalchemy/dialects/sqlite/base.py#L1200), which I think is the same as `sqlite3_column_decltype`.

**Comment by quinnj** [comment]
Yes, I've definitely wanted to do this.

**Comment by quinnj** [comment]
Hmmm......so part of the problem here is that `sqlite3_column_decltype` really only works for actual table columns. Any kind of expression column in a SELECT statement just returns null. I guess it can help in some cases to use decltype and then fallback to what we're doing now.

**Comment by quinnj** [comment]
Alrighty, we now use `sqlite3_column_decltype` first, with a fallback to `sqlite3_column_type` (the previous behavior). Tests all pass, and this actually solves an issue that was emailed to me personally about a problem reading a kaggle dataset: reporting the error below for posterity.

```julia
I'm sorry to address you by e-mail, but I don't have a github account to open a issue.

I was playing with a sqlite database from kaggle (https://www.kaggle.com/hugomathien/soccer/downloads/soccer.zip) and I get this error:


> db = SQLite.DB("database.sqlite")
> SQLite.query(db, "SELECT * FROM Match;");

ERROR: InexactError()
 in Nullable{Int64}(::Float64) at ./sysimg.jl:53
 in streamfrom(::SQLite.Source, ::Type{DataStreams.Data.Field}, ::Type{Nullable{Int64}}, ::Int64, ::Int64) at /home/am/.julia/v0.5/SQLite/src/Source.jl:83
 in streamto!(::DataFrames.DataFrame, ::Type{DataStreams.Data.Field}, ::SQLite.Source, ::Type{Nullable{Int64}}, ::Type{Nullable{Int64}}, ::Int64, ::Int64, ::DataStreams.Data.Schema{false}, ::Base.#identity) at /home/am/.julia/v0.5/DataStreams/src/DataStreams.jl:172
 in stream!(::SQLite.Source, ::Type{DataStreams.Data.Field}, ::DataFrames.DataFrame, ::DataStreams.Data.Schema{false}, ::DataStreams.Data.Schema{false}, ::Array{Function,1}) at /home/am/.julia/v0.5/DataStreams/src/DataStreams.jl:203
 in #stream!#5(::Array{Any,1}, ::Function, ::SQLite.Source, ::Type{DataFrames.DataFrame}, ::Bool, ::Dict{Int64,Function}) at /home/am/.julia/v0.5/DataStreams/src/DataStreams.jl:150
 in #query#16 at /home/am/.julia/v0.5/SQLite/src/Source.jl:119 [inlined]
 in query(::SQLite.DB, ::String, ::Type{DataFrames.DataFrame}) at /home/am/.julia/v0.5/SQLite/src/Source.jl:118
 in query(::SQLite.DB, ::String) at /home/am/.julia/v0.5/SQLite/src/Source.jl:111
```
