### ISSUE TITLE
removeduplicates! deletes all but a single row

### ISSUE THREAD

**Issue by amellnik** [JuliaDB/SQLite.jl#94]
A recent change somewhere in the pipeline is causing removeduplicates! to act strangely.  A simple example to reproduce is 

```julia
using SQLite
db = SQLite.DB() 
ints = Int64[1,1,2,2,3]
strs = UTF8String["A", "A", "B", "C", "C"]
nvInts = NullableArrays.NullableArray(ints)
nvStrs = NullableArrays.NullableArray(strs)
schema = DataStreams.Data.Schema(["ints", "strs"], [Int64, UTF8String],5)
d = NullableArrays.NullableVector[nvInts, nvStrs]
dt = DataStreams.Data.Table(schema, d,0)
SQLite.drop!(db, "temp", ifexists=true)
sink = SQLite.Sink(dt, db, "temp")
Data.stream!(dt, sink)
SQLite.query(db, "Select * from temp").data
```
```
2-element Array{NullableArrays.NullableArray{T,1},1}:
 NullableArrays.NullableArray{Int64,1}[1,1,2,2,3]               
 NullableArrays.NullableArray{UTF8String,1}["A","A","B","C","C"]
```
This is a two-column table with a single duplicate row out of five rows.  Running removeduplicates!:
```julia
SQLite.removeduplicates!(db, "temp", "ints, strs")
SQLite.query(db, "Select * from temp").data
```
```
2-element Array{NullableArrays.NullableArray{T,1},1}:
 NullableArrays.NullableArray{Int64,1}[3]       
 NullableArrays.NullableArray{UTF8String,1}["C"]
```
Removes all but the last row from the table for some reason.
Note that if you set up the table the same way and then do the same thing with the normal query function things work as expected:

```julia
SQLite.query(db, "DELETE FROM temp WHERE _ROWID_ NOT IN (SELECT max(_ROWID_) from temp GROUP BY ints, strs);")
SQLite.query(db, "Select * from temp").data
```
```
2-element Array{NullableArrays.NullableArray{T,1},1}:
 NullableArrays.NullableArray{Int64,1}[1,2,2,3]             
 NullableArrays.NullableArray{UTF8String,1}["A","B","C","C"]
```

I'm using the SQLite master and [this version of DataStreams](https://github.com/amellnik/DataStreams.jl/tree/dfconversion) which I think should be equivalent to to the master in this case.   One additional hint is that removing duplicates appears to work fine for tables with a single integer column.  

I'm still trying to figure out if this is due to some recent commit in SQLite or DataStreams, or if this is something that was broken by 0.4.2 or some other package.

**Comment by amellnik** [comment]
Ok, so it looks like the issue is with the internal function [```SQLite.esc_id```](https://github.com/JuliaDB/SQLite.jl/blob/29de2b6b4b21450236da05a6fc00868f8286c673/src/SQLite.jl#L190) which is used to escape identifiers.  It can accept a single string or a vector of strings, but [```removeduplicates!```](https://github.com/JuliaDB/SQLite.jl/blob/29de2b6b4b21450236da05a6fc00868f8286c673/src/SQLite.jl#L277) only allows a single string for the list of columns.  This means that when we call ```removeduplicates!(db, "temp", "ints, strs")``` the query that is actually executed is 
```
DELETE FROM "temp" WHERE _ROWID_ NOT IN (SELECT max(_ROWID_) from "temp" GROUP BY "ints, strs");
```
which breaks things since there is not a single column called ```"ints, strs"```.  This was probably introduced in  https://github.com/JuliaDB/SQLite.jl/commit/b367878bcc0e8624653944e48a0dec86b98f8ddb.  I think this can be fixed by adding an additional replace that adds quotes on either side of commas, and will give it a shot now.

**Comment by amellnik** [comment]
Fixing this is a bit more complicated than I thought.  The problem is that this method of adding escapes is not easily extended since you can have column names with spaces in them.  For example if someone set cols to ```"ints, strs"``` there's no way of knowing if the second column name is ```_strs``` or ```strs``` (where the underscore is a space), since either is a legal column name.  

It might be better to make cols be either a single column name or an array of column names rather than always a single string, although that would be a breaking change.  Any thoughts?

**Comment by quinnj** [comment]
yeah, I think we should require the columns argument to be an array of column name strings. For compatibility, we should probably make a single string argument an error for now, so peopel can transition.
