### ISSUE TITLE
Better printing of returned querysets

### ISSUE THREAD

**Issue by hayd** [JuliaDB/SQLite.jl#95]
Currently:
```
julia> db = SQLite.DB(); query(db, "CREATE TABLE t (c1 int, c2 string)"); query(db, "INSERT INTO t (c1, c2) VALUES (1, 'TWO'), (3, 'FOUR');"); query(db, "SELECT * FROM t")
Data.Table:
2x2 Data.Schema:
    c1,         c2
 Int64, UTF8String
NullableArrays.NullableArray{T,1}[NullableArrays.NullableArray{Int64,1}[1,3],NullableArrays.NullableArray{UTF8String,1}["TWO","FOUR"]]
```

I was wondering if it would be better to print something similar to as follows:

```
Data.Table:
2x2 Data.Schema:
    c1,         c2
 Int64, UTF8String
1	TWO
3	∅
```

This could be achieved with something like:

      function Base.show(io::IO, x::Vector{NullableVector})
        isempty(x) && return

         for i in 1:length(x[1])
           i == 1 || println()
           for col in x
             print(col[i].isnull ? "∅" : col[i].value, "\t")
           end
         end
       end

Thought there's probably a better way to do this than tabs (I'm sure this is a well-trodden problem), but thought I'd post my thoughts.

I realize that this came with [changes in Base](https://github.com/JuliaLang/julia/pull/14304#issuecomment-164822958) but it would be nice to improve this here (without necessarily extending Base.show).

**Comment by quinnj** [comment]
We now hook return a DataFrame by default which comes with a much more mature "show" experience
