### ISSUE TITLE
Error when create a new index

### ISSUE THREAD

**Issue by ignaciomartin** [JuliaDB/SQLite.jl#99]
When I try to create a new index by a unique col,
`SQLite.createindex!(resul, "Webs", "iFecha", "Fecha"; unique=true)`

 I get this error
`LoadError: SQLite.SQLiteException("near \"\"Fecha\"\": syntax error")
while loading In[51], in expression starting on line 2  in sqliteerror at D:\Usuarios\ignacio.martin\.julia\v0.4\SQLite\src\SQLite.jl:25`

Other information:
`methods(SQLite.createindex!)   
1 method for generic function createindex!:
    createindex!{S<:AbstractString}(db::SQLite.DB, table::AbstractString, index::AbstractString, cols::Union{AbstractArray{S<:AbstractString,1},S<:AbstractString}) at D:\Usuarios\ignacio.martin\.julia\v0.4\SQLite\src\SQLite.jl:267`

`Pkg.installed("SQLite")   
v"0.3.1+"`

Best regards.
Ignacio.

**Comment by ignaciomartin** [comment]
![image](https://cloud.githubusercontent.com/assets/19220563/15069966/8f675f78-1381-11e6-8d4f-9b8ed4283687.png)

**Comment by quinnj** [comment]
Yep, we were missing an ending parenthesis. I just pushed a commit that should fix it. If you do
```julia
Pkg.checkout("SQLite")
```
you should get teh fix.
